services:
  database:
    image: mongo:8.0
    container_name: sec-mongodb
    expose: 
      - "27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  backend-api:
    build: ./backend
    container_name: sec-backend
    expose:
      - "8000"
    environment: 
      - MONGO_URL=mongodb://database:27017
    depends_on:
      - database
    restart: always

  reverse-proxy:
    image: nginx:alpine
    container_name: sec-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-api 
    restart: always


volumes:
  mongo_data: